[package]
name = "exchange-pb"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.12"
prost-types = "0.12"
bytes = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
prost-build = "0.12"